spring:
  application:
    name: cards
  flyway:
    enabled: true
  jpa:
    show-sql: true
  config:
    import: configserver:http://config-service:8888
  cloud:
    bus:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
