spring:
  application:
    name: loans
    flyway:
      enabled: true
    jpa:
      show-sql: true
  cloud:
    config:
      uri:
    bus:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
