spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/loans
    username: postgres
    password: postgres
  config:
    import: configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9002