spring:
  application:
    name: loans
    flyway:
      enabled: true
    jpa:
      show-sql: true
  cloud:
    config:
      uri:
    bus:
      enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
