spring:
  application:
    name: accounts
  datasource:
    url: jdbc:postgresql://accounts-db:5432/accounts
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jpa:
    show-sql: true

server:
  port: 8080
