spring:
  application:
    name: accounts
  flyway:
    enabled: true
  jpa:
    show-sql: true
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    bus:
      enabled: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
