spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vadymfomin95/BankProject
          default-label: main
          clone-on-start: true
          timeout: 5
          search-paths: config/*
          force-pull: true
          skip-ssl-validation: true
    bus:
      enabled: true
server:
  port: 8888

truststore:
  path: file:server_truststore.jks
  password: changeit

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

